# -*- coding: utf-8 -*-
"""Code_Pembelajaran Mesin_ Kelompok 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1be-wp6G7RnICJCYAo4JOwd42gwzMOkIQ

# **Implementasi dan Analisis Komparatif MobileNet, ResNet, dan CNN-MLP untuk Klasifikasi Penyakit Daun Padi**

Kelompok 8:
- Ahmad Dhani Alfawwas (24031554096)
- Maria Agatha Metri Tetrajati (24031554189)
- Tara Tabriza Rachman (24031554107)

Rumusan Masalah : 1.2 Lambatnya Adopsi Teknologi dan Transformasi Digital dalam Ekosistem Pangan





---
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## **Dataset**

### **1. Inisialisasi Dataset**
"""

base_path = '/content/drive/MyDrive/Dataset Final Project_ML/archive (38)/rice'

# Daftar nama kelas sesuai urutan ID 0-8
class_names = [
    "BacterialLeafBlight", "BrownSpot", "Healthy", "Hispa",
    "LeafBlast", "LeafScald", "LeafSmut", "NarrowBrownLeafSpot", "NeckBlast"
]

all_data = []
print(f"Dataset path: {base_path}")

"""### **2. Ekstraksi Data dari File Anotasi (.txt)**"""

print("Sedang memindai seluruh folder untuk data keseluruhan...")
for root, dirs, files in os.walk(base_path):
    if 'labels' in root:
        # Mengambil nama folder induk dari 'labels'
        split_name = os.path.basename(os.path.dirname(root))
        for filename in files:
            if filename.endswith(".txt"):
                with open(os.path.join(root, filename), 'r') as f:
                    lines = f.readlines()
                    for line in lines:
                        parts = line.split()
                        if len(parts) > 0:
                            class_id = int(parts[0])
                            if class_id < len(class_names):
                                all_data.append({
                                    'class_name': class_names[class_id],
                                    'split': split_name
                                })

df_all = pd.DataFrame(all_data)
print(f"Selesai! Total instance objek ditemukan: {len(df_all)}")

"""### **3. Visualisasi Histogram Gabungan**"""

plt.figure(figsize=(14, 7))
sns.set_style("whitegrid")

order = df_all['class_name'].value_counts().index
ax = sns.countplot(data=df_all, x='class_name', order=order, hue='split', palette='viridis')

plt.title('Distribusi Keseluruhan Label Penyakit Padi', fontsize=16)
plt.xlabel('Jenis Penyakit', fontsize=12)
plt.ylabel('Total Label (Bounding Boxes)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Dataset Split')

for p in ax.patches:
    if p.get_height() > 0:
        ax.annotate(f'{int(p.get_height())}',
                    (p.get_x() + p.get_width() / 2., p.get_height()),
                    ha = 'center', va = 'center',
                    xytext = (0, 9),
                    textcoords = 'offset points',
                    fontsize=9)

plt.tight_layout()
plt.show()

print("="*50)
print("TABEL DISTRIBUSI TOTAL")
print("="*50)
summary = pd.crosstab(df_all['class_name'], df_all['split'], margins=True, margins_name="TOTAL")
display(summary.sort_values(by='TOTAL', ascending=False))