# -*- coding: utf-8 -*-
"""Data Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqA1AYt0G9jBDoJq_IvJXPxHZ39EqR35
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
import random

# PATH data train
base_path = '/content/drive/Shareddrives/Dataset Padi_ML/archive (38)/rice'

INPUT_DIR = os.path.join(
    base_path,
    'classification_dataset_adaptive'
)
OUTPUT_DIR = os.path.join(
    base_path,
    'classification_dataset_preprocessed'
)

IMG_SIZE = 224

os.makedirs(OUTPUT_DIR, exist_ok=True)

# =========================
# PREPROCESS FUNCTION
# =========================
def preprocess_image(img):

    # Resize
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    # =====================
    # CLAHE
    # =====================
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

    l, a, b = cv2.split(lab)

    clahe = cv2.createCLAHE(
        clipLimit=2.0,
        tileGridSize=(8, 8)
    )

    l = clahe.apply(l)

    lab = cv2.merge((l, a, b))

    img = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

    # =====================
    # Sharpen ringan
    # =====================
    kernel = np.array([
        [0, -1, 0],
        [-1, 5, -1],
        [0, -1, 0]
    ])

    img = cv2.filter2D(img, -1, kernel)

    return img

# =========================
# PROCESS DATASET
# =========================
for class_name in os.listdir(INPUT_DIR):

    class_input = os.path.join(INPUT_DIR, class_name)

    if not os.path.isdir(class_input):
        continue

    class_output = os.path.join(OUTPUT_DIR, class_name)
    os.makedirs(class_output, exist_ok=True)

    image_files = os.listdir(class_input)

    print(f"\nProcessing {class_name}")

    for img_name in tqdm(image_files):

        img_path = os.path.join(class_input, img_name)

        img = cv2.imread(img_path)

        if img is None:
            continue

        img = preprocess_image(img)

        save_path = os.path.join(class_output, img_name)

        cv2.imwrite(save_path, img)

print("\nPREPROCESSING SELESAI")

# PATH validation data
base_path = '/content/drive/Shareddrives/Dataset Padi_ML/archive (38)/rice'

INPUT_DIR = os.path.join(
    base_path,
    'val_dataset_adaptive'
)
OUTPUT_DIR = os.path.join(
    base_path,
    'val_dataset_preprocessed'
)

IMG_SIZE = 224

os.makedirs(OUTPUT_DIR, exist_ok=True)

# =========================
# PREPROCESS FUNCTION
# =========================
def preprocess_image(img):

    # Resize
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    # =====================
    # CLAHE
    # =====================
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

    l, a, b = cv2.split(lab)

    clahe = cv2.createCLAHE(
        clipLimit=2.0,
        tileGridSize=(8, 8)
    )

    l = clahe.apply(l)

    lab = cv2.merge((l, a, b))

    img = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

    # =====================
    # Sharpen ringan
    # =====================
    kernel = np.array([
        [0, -1, 0],
        [-1, 5, -1],
        [0, -1, 0]
    ])

    img = cv2.filter2D(img, -1, kernel)

    return img

# =========================
# PROCESS DATASET
# =========================
for class_name in os.listdir(INPUT_DIR):

    class_input = os.path.join(INPUT_DIR, class_name)

    if not os.path.isdir(class_input):
        continue

    class_output = os.path.join(OUTPUT_DIR, class_name)
    os.makedirs(class_output, exist_ok=True)

    image_files = os.listdir(class_input)

    print(f"\nProcessing {class_name}")

    for img_name in tqdm(image_files):

        img_path = os.path.join(class_input, img_name)

        img = cv2.imread(img_path)

        if img is None:
            continue

        img = preprocess_image(img)

        save_path = os.path.join(class_output, img_name)

        cv2.imwrite(save_path, img)

print("\nPREPROCESSING SELESAI")

# PATH Dataset eksternal test
base_path = '/content/drive/Shareddrives/Dataset Padi_ML/archive (38)/rice'

INPUT_DIR = os.path.join(
    base_path,
    'rice_leaf_diseases'
)
OUTPUT_DIR = os.path.join(
    base_path,
    'val_rice'
)

IMG_SIZE = 224

os.makedirs(OUTPUT_DIR, exist_ok=True)

# =========================
# PREPROCESS FUNCTION
# =========================
def preprocess_image(img):

    # Resize
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    # =====================
    # CLAHE
    # =====================
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

    l, a, b = cv2.split(lab)

    clahe = cv2.createCLAHE(
        clipLimit=2.0,
        tileGridSize=(8, 8)
    )

    l = clahe.apply(l)

    lab = cv2.merge((l, a, b))

    img = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

    # =====================
    # Sharpen ringan
    # =====================
    kernel = np.array([
        [0, -1, 0],
        [-1, 5, -1],
        [0, -1, 0]
    ])

    img = cv2.filter2D(img, -1, kernel)

    return img

# =========================
# PROCESS DATASET
# =========================
for class_name in os.listdir(INPUT_DIR):

    class_input = os.path.join(INPUT_DIR, class_name)

    if not os.path.isdir(class_input):
        continue

    class_output = os.path.join(OUTPUT_DIR, class_name)
    os.makedirs(class_output, exist_ok=True)

    image_files = os.listdir(class_input)

    print(f"\nProcessing {class_name}")

    for img_name in tqdm(image_files):

        img_path = os.path.join(class_input, img_name)

        img = cv2.imread(img_path)

        if img is None:
            continue

        img = preprocess_image(img)

        save_path = os.path.join(class_output, img_name)

        cv2.imwrite(save_path, img)

print("\nPREPROCESSING SELESAI")