# -*- coding: utf-8 -*-
"""Data Preparation Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1bC5zGEkkDtje3ZsK8XPck35BhFOG8a

# **Implementasi dan Analisis Komparatif MobileNet, ResNet, dan CNN-MLP untuk Klasifikasi Penyakit Daun Padi**

Kelompok 8:
- Ahmad Dhani Alfawwas (24031554096)
- Maria Agatha Metri Tetrajati (24031554189)
- Tara Tabriza Rachman (24031554107)

Rumusan Masalah : 1.2 Lambatnya Adopsi Teknologi dan Transformasi Digital dalam Ekosistem Pangan





---
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
import random

"""##**Path Dataset**"""

IMAGE_DIR = os.path.join(base_path, 'images', 'train')
LABEL_DIR = os.path.join(base_path, 'labels', 'train')

print("IMAGE_DIR:", IMAGE_DIR)
print("LABEL_DIR:", LABEL_DIR)

print("Jumlah image:", len(os.listdir(IMAGE_DIR)))
print("Jumlah label:", len(os.listdir(LABEL_DIR)))

base_path = '/content/drive/Shareddrives/Dataset Padi_ML/archive (38)/rice'

IMAGE_DIR = os.path.join(base_path, 'images', 'train')
LABEL_DIR = os.path.join(base_path, 'labels', 'train')

"""## **Menentukan Threshold untuk Expanded Cropping**"""

sample_size = 300

all_images = [
    f for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith(('.jpg', '.jpeg', '.png'))
]

# Random sample
sample_images = random.sample(
    all_images,
    min(sample_size, len(all_images))
)

print(f"Total sample image: {len(sample_images)}")

# Simpan Data Ratio
bbox_ratios = []

# Process Sample
for image_file in sample_images:

    image_path = os.path.join(IMAGE_DIR, image_file)

    label_file = os.path.splitext(image_file)[0] + '.txt'
    label_path = os.path.join(LABEL_DIR, label_file)

    if not os.path.exists(label_path):
        continue

    image = cv2.imread(image_path)

    if image is None:
        continue

    img_h, img_w = image.shape[:2]

    with open(label_path, 'r') as f:
        lines = f.readlines()

    for line in lines:

        data = line.strip().split()

        # YOLO detection format only
        if len(data) != 5:
            continue

        width = float(data[3]) * img_w
        height = float(data[4]) * img_h

        area_ratio = (
            (width * height) /
            (img_w * img_h)
        )

        bbox_ratios.append(area_ratio)

# Histogram
plt.figure(figsize=(10,5))

plt.hist(bbox_ratios, bins=50)

plt.xlabel("BBox Area Ratio")
plt.ylabel("Count")
plt.title("Random Sample BBox Distribution")

plt.show()

# Statistik
print("\n===== STATISTIK =====")

print("Jumlah bbox :", len(bbox_ratios))

print("\nMIN     :", np.min(bbox_ratios))
print("MAX     :", np.max(bbox_ratios))
print("MEAN    :", np.mean(bbox_ratios))
print("MEDIAN  :", np.median(bbox_ratios))

print("\n===== PERCENTILE =====")

print("10% :", np.percentile(bbox_ratios, 10))
print("25% :", np.percentile(bbox_ratios, 25))
print("50% :", np.percentile(bbox_ratios, 50))
print("75% :", np.percentile(bbox_ratios, 75))
print("90% :", np.percentile(bbox_ratios, 90))

"""## **Melakukan Cropping dengan Threshold**"""

OUTPUT_DIR = os.path.join(base_path, 'classification_dataset_adaptive')

# Class
class_names = [
    "BacterialLeafBlight",
    "BrownSpot",
    "Healthy",
    "Hispa",
    "LeafBlast",
    "LeafScald",
    "LeafSmut",
    "NarrowBrownLeafSpot",
    "NeckBlast"
]

# Buat Folder Output
for class_name in class_names:
    os.makedirs(
        os.path.join(OUTPUT_DIR, class_name),
        exist_ok=True
    )

# Yolo --> Pixel
def yolo_to_pixel(x_center, y_center, width, height, img_w, img_h):

    x_center = x_center * img_w
    y_center = y_center * img_h
    width = width * img_w
    height = height * img_h

    x1 = int(x_center - width / 2)
    y1 = int(y_center - height / 2)
    x2 = int(x_center + width / 2)
    y2 = int(y_center + height / 2)

    return x1, y1, x2, y2


image_files = os.listdir(IMAGE_DIR)

print(f"Total image ditemukan: {len(image_files)}")

# Counter
total_crop = 0
skip_tiny = 0

# Processing
for image_file in tqdm(image_files):

    # Skip non-image
    if not image_file.lower().endswith(('.jpg', '.jpeg', '.png')):
        continue

    image_path = os.path.join(IMAGE_DIR, image_file)

    label_file = os.path.splitext(image_file)[0] + '.txt'
    label_path = os.path.join(LABEL_DIR, label_file)

    # Skip jika label tidak ada
    if not os.path.exists(label_path):
        continue

    image = cv2.imread(image_path)

    if image is None:
        continue

    img_h, img_w = image.shape[:2]

    with open(label_path, 'r') as f:
        lines = f.readlines()

    for idx, line in enumerate(lines):

        data = line.strip().split()

        # YOLO DETECTION FORMAT ONLY
        if len(data) != 5:
            continue

        class_id = int(data[0])

        # Skip invalid class
        if class_id >= len(class_names):
            continue

        x_center = float(data[1])
        y_center = float(data[2])
        width = float(data[3])
        height = float(data[4])

        x1, y1, x2, y2 = yolo_to_pixel(
            x_center,
            y_center,
            width,
            height,
            img_w,
            img_h
        )

        # BBOX Size
        bbox_w = x2 - x1
        bbox_h = y2 - y1

        bbox_area_ratio = (
            (bbox_w * bbox_h) /
            (img_w * img_h)
        )

        # Skip super tiny BBOX
        if bbox_area_ratio < 0.0005:
            skip_tiny += 1
            continue

        if bbox_area_ratio < 0.005:
            expand_ratio = 3.0

        elif bbox_area_ratio < 0.02:
            expand_ratio = 2.0

        elif bbox_area_ratio < 0.1:
            expand_ratio = 1.0

        else:
            expand_ratio = 0.2

        # Expand BBOX

        pad_w = int(bbox_w * expand_ratio)
        pad_h = int(bbox_h * expand_ratio)

        x1 -= pad_w
        y1 -= pad_h
        x2 += pad_w
        y2 += pad_h

        # Clamp
        x1 = max(0, x1)
        y1 = max(0, y1)
        x2 = min(img_w, x2)
        y2 = min(img_h, y2)

        # Crop Image
        cropped = image[y1:y2, x1:x2]

        # Skip empty crop
        if cropped.size == 0:
            continue

        class_name = class_names[class_id]

        output_filename = (
            f"{os.path.splitext(image_file)[0]}_{idx}.jpg"
        )

        output_path = os.path.join(
            OUTPUT_DIR,
            class_name,
            output_filename
        )

        cv2.imwrite(output_path, cropped)

        total_crop += 1

print("\n===================================")
print(f"TOTAL CROPPED IMAGES : {total_crop}")
print(f"SUPER TINY SKIPPED   : {skip_tiny}")
print("CONVERSION SELESAI")
print("===================================")

"""## **Visualisasi Hasil Crop**"""

import os
import matplotlib.pyplot as plt
from collections import Counter

base_path = '/content/drive/Shareddrives/Dataset Padi_ML/archive (38)/rice'

DATASET_DIR = os.path.join(
    base_path,
    'classification_dataset_adaptive'
)

# Hitung Distribusi Label
label_counts = {}

for class_name in os.listdir(DATASET_DIR):

    class_path = os.path.join(DATASET_DIR, class_name)

    if not os.path.isdir(class_path):
        continue

    total_images = len([
        f for f in os.listdir(class_path)
        if f.lower().endswith(('.jpg', '.jpeg', '.png'))
    ])

    label_counts[class_name] = total_images

# Sorting
label_counts = dict(
    sorted(
        label_counts.items(),
        key=lambda x: x[1],
        reverse=True
    )
)


print("\n===== DISTRIBUSI LABEL =====\n")

for label, count in label_counts.items():
    print(f"{label:<25} : {count}")

# Visualisasi Histogram
plt.figure(figsize=(14,6))

bars = plt.bar(
    label_counts.keys(),
    label_counts.values()
)

# Tambahkan angka di atas bar
for bar in bars:

    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f'{height}',
        ha='center',
        va='bottom',
        fontsize=10
    )

plt.title(
    'Distribusi Label Classification Dataset',
    fontsize=18
)

plt.xlabel('Class Label', fontsize=14)
plt.ylabel('Jumlah Gambar', fontsize=14)

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()