# -*- coding: utf-8 -*-
"""Training Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xiE-wqd8t8GLWnjc063Tui0_HYZ-Xzs
"""
"""
# **Implementasi dan Analisis Komparatif MobileNetV3, ResNet, dan CNN-MLP untuk Klasifikasi Penyakit Daun Padi**

Kelompok 8:
- Ahmad Dhani Alfawwas (24031554096)
- Maria Agatha Metri Tetrajati (24031554189)
- Tara Tabriza Rachman (24031554107)

Rumusan Masalah : 1.2 Lambatnya Adopsi Teknologi dan Transformasi Digital dalam Ekosistem Pangan





---
"""

import os
import torch
import numpy as np

from torchvision import datasets, transforms
from torchvision.models import mobilenet_v3_large

from torch.utils.data import DataLoader
from sklearn.utils.class_weight import compute_class_weight

import torch.nn as nn
import torch.optim as optim

import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

base_path = '/content/drive/Shareddrives/Dataset Padi_ML/archive (38)'

DATASET_DIR = os.path.join(
    base_path,
    'rice'
)

TRAIN_DIR = os.path.join(DATASET_DIR, 'classification_dataset_preprocessed')
VAL_DIR = os.path.join(DATASET_DIR, 'val_dataset_preprocessed')

"""# Pipeline"""

# train transform
train_transform = transforms.Compose([

    transforms.RandomHorizontalFlip(),

    transforms.RandomRotation(15),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# validation transform
val_transform = transforms.Compose([

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# dataset
train_dataset = datasets.ImageFolder(
    TRAIN_DIR,
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=val_transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

class_names = train_dataset.classes

print(class_names)

# class_weights
labels = train_dataset.targets

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(labels),
    y=labels
)

class_weights = torch.tensor(
    class_weights,
    dtype=torch.float
)

print(class_weights)

# device
device = torch.device(
    'cuda' if torch.cuda.is_available() else 'cpu'
)

print(device)

#model
model = mobilenet_v3_large(pretrained=True)

# ganti classifier output
model.classifier[3] = nn.Linear(
    model.classifier[3].in_features,
    5
)

model = model.to(device)

# loss & optimizer
criterion = nn.CrossEntropyLoss(
    weight=class_weights.to(device)
)

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

# Visualisasi

class_names = train_dataset.classes

labels = np.array(train_dataset.targets)
unique_labels, sample_counts = np.unique(labels, return_counts=True)

weights_array = class_weights.cpu().numpy()

plt.style.use('seaborn-v0_8-whitegrid')
fig, ax1 = plt.subplots(figsize=(14, 7))

x = np.arange(len(class_names))
width = 0.35

bars1 = ax1.bar(x - width/2, sample_counts, width, label='Jumlah Sampel Asli', color='#3498db', edgecolor='black')
ax1.set_xlabel('Kelas Penyakit Daun Padi', fontsize=12, fontweight='bold')
ax1.set_ylabel('Jumlah Gambar (Distribusi Asli)', color='#2980b9', fontsize=12, fontweight='bold')
ax1.tick_params(axis='y', labelcolor='#2980b9')
ax1.set_xticks(x)
ax1.set_xticklabels(class_names, rotation=30, ha='right')

ax2 = ax1.twinx()  # Membuat sumbu Y kedua yang berbagi sumbu X yang sama
bars2 = ax2.bar(x + width/2, weights_array, width, label='Bobot Kelas (Class Weight)', color='#e74c3c', edgecolor='black')
ax2.set_ylabel('Multiplier Bobot (Penalti Loss)', color='#c0392b', fontsize=12, fontweight='bold')
ax2.tick_params(axis='y', labelcolor='#c0392b')

for bar in bars2:
    yval = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2, yval + 0.1, f'{yval:.2f}x', ha='center', va='bottom', fontsize=10, fontweight='bold', color='#c0392b')

plt.title('Evaluasi Penanganan Imbalance Data dengan Metode Class Weights', fontsize=16, fontweight='bold', pad=20)
fig.legend(loc='upper right', bbox_to_anchor=(0.9, 0.85), fontsize=12)

plt.text(0.5, -0.3, "Interpretasi: Kelas minoritas (batang biru pendek) secara otomatis diberikan bobot penalti (batang merah) yang jauh lebih tinggi.",
         ha='center', transform=ax1.transAxes, fontsize=12, style='italic')

plt.tight_layout()
plt.show()

"""# Training"""

from tqdm import tqdm

# =========================
# TRAIN FUNCTION
# =========================
def train_one_epoch(model, loader, optimizer, criterion, device):

    model.train()

    running_loss = 0
    correct = 0
    total = 0

    loop = tqdm(loader)

    for images, labels in loop:

        images = images.to(device)
        labels = labels.to(device)

        # zero grad
        optimizer.zero_grad()

        # forward
        outputs = model(images)

        loss = criterion(outputs, labels)

        # backward
        loss.backward()

        optimizer.step()

        # statistics
        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

        acc = 100 * correct / total

        loop.set_postfix(
            loss=loss.item(),
            acc=acc
        )

    epoch_loss = running_loss / len(loader)
    epoch_acc = 100 * correct / total

    return epoch_loss, epoch_acc


# =========================
# VALIDATION FUNCTION
# =========================
def validate(model, loader, criterion, device):

    model.eval()

    running_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            running_loss += loss.item()

            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)

            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(loader)
    epoch_acc = 100 * correct / total

    return epoch_loss, epoch_acc

# main training
NUM_EPOCHS = 15

best_val_acc = 0

train_losses = []
val_losses = []

train_accuracies = []
val_accuracies = []

for epoch in range(NUM_EPOCHS):

    print(f"\nEpoch {epoch+1}/{NUM_EPOCHS}")

    # =====================
    # TRAIN
    # =====================
    train_loss, train_acc = train_one_epoch(
        model,
        train_loader,
        optimizer,
        criterion,
        device
    )

    # =====================
    # VALIDATE
    # =====================
    val_loss, val_acc = validate(
        model,
        val_loader,
        criterion,
        device
    )

    # =====================
    # SAVE HISTORY
    # =====================
    train_losses.append(train_loss)
    val_losses.append(val_loss)

    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)

    print(f"Train Loss : {train_loss:.4f}")
    print(f"Train Acc  : {train_acc:.2f}%")

    print(f"Val Loss   : {val_loss:.4f}")
    print(f"Val Acc    : {val_acc:.2f}%")

    # =====================
    # SAVE BEST MODEL
    # =====================
    if val_acc > best_val_acc:

        best_val_acc = val_acc

        torch.save(
            model.state_dict(),
            'best_mobilenetv3.pth'
        )

        print("Best model saved!")

model.load_state_dict(
    torch.load('best_mobilenetv3.pth')
)

import matplotlib.pyplot as plt

# =========================
# LOSS GRAPH
# =========================
plt.figure(figsize=(10,5))

plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Validation Loss')

plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.title('Training vs Validation Loss')

plt.legend()

plt.grid(True)

plt.show()

# =========================
# ACCURACY GRAPH
# =========================
plt.figure(figsize=(10,5))

plt.plot(train_accuracies, label='Train Accuracy')
plt.plot(val_accuracies, label='Validation Accuracy')

plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')

plt.title('Training vs Validation Accuracy')

plt.legend()

plt.grid(True)

plt.show()

"""# evaluasi"""

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

all_preds = []
all_labels = []

model.eval()

with torch.no_grad():

    for images, labels in val_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print(classification_report(
    all_labels,
    all_preds,
    target_names=class_names
))

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""# Eksternal test"""

import os
import torch
import seaborn as sns
import matplotlib.pyplot as plt

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

from sklearn.metrics import (
    classification_report,
    confusion_matrix
)

TEST_DIR = os.path.join(DATASET_DIR, 'val_rice')

test_transform = transforms.Compose([

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

test_dataset = datasets.ImageFolder(
    TEST_DIR,
    transform=test_transform
)

print(test_dataset.classes)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

model.load_state_dict(
    torch.load('best_mobilenetv3.pth')
)

model.eval()

all_preds = []
all_labels = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print(classification_report(
    all_labels,
    all_preds,
    labels=[0,1,2],
    target_names=test_dataset.classes
))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    all_labels,
    all_preds,
    labels=[0,1,2]
)

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix

# =====================================
# CONFUSION MATRIX
# =====================================
cm = confusion_matrix(
    all_labels,
    all_preds
)

# =====================================
# PLOT
# =====================================
plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=test_dataset.classes,
    yticklabels=test_dataset.classes
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.title("External Test Confusion Matrix")

plt.show()
